#!/usr/bin/env python3
# Generates stratosphere/boot/source/boot_loading_assets.inc for the Ryazhenka
# boot loading screen (clean chat style, typewriter reveal).
#
# Each line is baked as one RGBA bitmap (alpha in high byte, 0xAARRGGBB) plus a
# per-character cut table (pixel width after each character) so the boot module
# can reveal it letter-by-letter. Plus a small green "OK" bitmap.
#
# Run from the repo root:  python3 scripts/gen_loading_assets.py
import os
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
OUT  = "stratosphere/boot/source/boot_loading_assets.inc"
SIZE = 24
PAD  = 2

TEXT = (230, 232, 239, 255)   # clean cool white
OKC  = (61, 220, 132, 255)    # soft green

LINES = [
    "Загрузка ресурсов Ryazhenka",
    "Проверка модулей (AOTag/OC)",
    "Загрузка KIP",
    "Синхронизация модулей",
    "Запуск Ryazhenka",
]

font = ImageFont.truetype(FONT, SIZE)
asc, desc = font.getmetrics()
CELL_H = asc + desc + 2 * PAD

def render_line(text):
    # Uniform height cell, baseline-aligned; left padded by PAD.
    tmp = Image.new("RGBA", (4, 4)); d = ImageDraw.Draw(tmp)
    width = int(d.textlength(text, font=font)) + 2 * PAD
    img = Image.new("RGBA", (width, CELL_H), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.text((PAD, PAD), text, font=font, fill=TEXT)
    # per-character cut positions (pixel width revealed after k+1 chars)
    cuts = []
    for k in range(1, len(text) + 1):
        w = PAD + int(round(d.textlength(text[:k], font=font)))
        cuts.append(min(w, width))
    return width, CELL_H, img, cuts

def render_word(text, color):
    tmp = Image.new("RGBA", (4, 4)); d = ImageDraw.Draw(tmp)
    l, t, r, b = d.textbbox((0, 0), text, font=font)
    w, h = (r - l) + 2 * PAD, (b - t) + 2 * PAD
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.text((PAD - l, PAD - t), text, font=font, fill=color)
    return w, h, img

def u32(img):
    px = img.load(); w, h = img.size; out = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            out.append((a << 24) | (r << 16) | (g << 8) | b)
    return out

with open(OUT, "w") as f:
    f.write("/* Auto-generated by scripts/gen_loading_assets.py. Do not edit by hand. */\n")
    for i, s in enumerate(LINES):
        w, h, img, cuts = render_line(s)
        f.write("constexpr u32 line%d_d[%d] = {%s};\n" % (i, w * h, ",".join("0x%08X" % v for v in u32(img))))
        f.write("constexpr u32 line%d_cuts[%d] = {%s};\n" % (i, len(cuts), ",".join(str(c) for c in cuts)))
        f.write("constexpr LoadLine LoadLine%d = { %d, %d, line%d_d, %d, line%d_cuts };\n" % (i, w, h, i, len(cuts), i))
    f.write("constexpr LoadLine LoadLines[%d] = { %s };\n" %
            (len(LINES), ", ".join("LoadLine%d" % i for i in range(len(LINES)))))
    w, h, img = render_word("OK", OKC)
    f.write("constexpr u32 ok_d[%d] = {%s};\n" % (w * h, ",".join("0x%08X" % v for v in u32(img))))
    f.write("constexpr LoadImg LoadOk = { %d, %d, ok_d };\n" % (w, h))

print("cell_h", CELL_H, "lines", len(LINES))
print("wrote", OUT, "%.0f KB" % (os.path.getsize(OUT) / 1024))
