#!/usr/bin/env python3
# Generates stratosphere/boot/source/boot_loading_assets.inc:
# small RGBA bitmaps (alpha in high byte, 0xAARRGGBB) for the Ryazhenka boot
# loading screen — title, checklist labels, digit/%/OK/dots glyphs.
#
# Run from the repo root:  python3 scripts/gen_loading_assets.py
import os
from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
OUT  = "stratosphere/boot/source/boot_loading_assets.inc"

# "Milky" palette (RGBA).
CREAM   = (243, 236, 221, 255)
CREAM_T = (245, 241, 231, 255)
GREEN   = (85, 201, 122, 255)
DIM     = (168, 158, 138, 255)

TITLE      = "СИСТЕМА ЗАГРУЖАЕТСЯ.."
LABELS = [
    "ЗАГРУЗКА РЕСУРСОВ RYAZHENKA",
    "ПРОВЕРКА МОДУЛЕЙ (AOTag/OC)",
    "ЗАГРУЗКА KIP",
    "СИНХРОНИЗАЦИЯ МОДУЛЕЙ",
    "ЗАПУСК RYAZHENKA",
]

def render(text, size, color):
    font = ImageFont.truetype(FONT, size)
    # measure
    tmp = Image.new("RGBA", (4, 4), (0, 0, 0, 0))
    d = ImageDraw.Draw(tmp)
    l, t, r, b = d.textbbox((0, 0), text, font=font)
    w, h = (r - l) + 4, (b - t) + 4
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.text((2 - l, 2 - t), text, font=font, fill=color)
    return img

def to_u32(img):
    px = img.load()
    w, h = img.size
    vals = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            vals.append((a << 24) | (r << 16) | (g << 8) | b)
    return w, h, vals

assets = {}              # name -> (w,h,vals)
assets["LoadTitle"] = to_u32(render(TITLE, 40, CREAM_T))
for i, s in enumerate(LABELS):
    assets["LoadLabel%d" % i] = to_u32(render(s, 28, CREAM))
assets["LoadOk"]   = to_u32(render("OK", 28, GREEN))
assets["LoadDots"] = to_u32(render("...", 28, DIM))
assets["LoadPercent"] = to_u32(render("%", 36, CREAM_T))

# Digits rendered to a uniform cell (monospaced) for clean alignment.
digit_imgs = [render(str(n), 36, CREAM_T) for n in range(10)]
cell_w = max(im.size[0] for im in digit_imgs)
cell_h = max(im.size[1] for im in digit_imgs)
digits = []
for im in digit_imgs:
    cell = Image.new("RGBA", (cell_w, cell_h), (0, 0, 0, 0))
    cell.alpha_composite(im, ((cell_w - im.size[0]) // 2, (cell_h - im.size[1]) // 2))
    digits.append(to_u32(cell))
for n in range(10):
    assets["LoadDigit%d" % n] = digits[n]

def emit_array(f, name, w, h, vals):
    f.write("constexpr u32 %s_d[%d] = {" % (name, len(vals)))
    f.write(",".join("0x%08X" % v for v in vals))
    f.write("};\n")

with open(OUT, "w") as f:
    f.write("/* Auto-generated by scripts/gen_loading_assets.py. Do not edit by hand. */\n")
    for name, (w, h, vals) in assets.items():
        emit_array(f, name, w, h, vals)
    f.write("\n")
    for name, (w, h, vals) in assets.items():
        f.write("constexpr LoadImg %s = { %d, %d, %s_d };\n" % (name, w, h, name))
    f.write("\nconstexpr LoadImg LoadLabels[5] = { %s };\n" %
            ", ".join("LoadLabel%d" % i for i in range(5)))
    f.write("constexpr LoadImg LoadDigits[10] = { %s };\n" %
            ", ".join("LoadDigit%d" % i for i in range(10)))

print("max label width:", max(assets["LoadLabel%d" % i][0] for i in range(5)))
print("title size:", assets["LoadTitle"][0], assets["LoadTitle"][1])
print("digit cell:", cell_w, cell_h)
print("wrote", OUT, "%.0f KB" % (os.path.getsize(OUT)/1024))
